services:
  php:
    image: php-app:latest
    build:
      context: .
      args:
        APP_URL: ${APP_URL}
        APP_NAME: ${APP_NAME}
        REVERB_APP_KEY: ${REVERB_APP_KEY}
        VITE_REVERB_HOST: ${VITE_REVERB_HOST}
    environment:
      PHP_OPCACHE_ENABLE: 1
      AUTORUN_ENABLED: true
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/up" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      - "storage_private:/var/www/html/storage/app/private/"
      - "storage_public:/var/www/html/storage/app/public/"
      - "storage_sessions:/var/www/html/storage/framework/sessions"
      - "storage_logs:/var/www/html/storage/logs"


  reverb:
    depends_on:
      - php
    image: php-app:latest
    environment:
      PHP_OPCACHE_ENABLE: 1
      AUTORUN_ENABLED: false
      LOG_CHANNEL: stderr
    command: [ "php", "/var/www/html/artisan", "reverb:start" ]
    stop_signal: SIGTERM
    healthcheck:
      test: [ "CMD", "healthcheck-reverb" ]
      start_period: 10s
    volumes:
      - "reverb_storage_private:/var/www/html/storage/app/private/"
      - "reverb_storage_public:/var/www/html/storage/app/public/"
      - "reverb_storage_sessions:/var/www/html/storage/framework/sessions"
      - "reverb_storage_logs:/var/www/html/storage/logs"

  queue:
    depends_on:
      - php
    image: php-app:latest
    environment:
      PHP_OPCACHE_ENABLE: 1
      LOG_CHANNEL: stderr
    command: [ "php", "/var/www/html/artisan", "queue:work", "--tries=3" ]
    stop_signal: SIGTERM
    volumes:
      - "queue_storage_logs:/var/www/html/storage/logs"
    healthcheck:
      test: [ "CMD", "healthcheck-queue" ]
      start_period: 10s


#  chromium:
#    image: zenika/alpine-chrome
#    command: [ chromium-browser, "--headless", "--disable-gpu", "--remote-debugging-address=0.0.0.0", "--remote-debugging-port=9222" ]
#    exclude_from_hc: true
#    cap_add:
#      - SYS_ADMIN
#    networks:
#      chromium_net:
#        ipv4_address: 172.99.0.100

networks:
  chromium_net:
    ipam:
      driver: default
      config:
        - subnet: "172.99.0.0/24"

volumes:
  certificates:
  storage_private:
  storage_public:
  storage_sessions:
  storage_logs:

  reverb_storage_private:
  reverb_storage_public:
  reverb_storage_sessions:
  reverb_storage_logs:

  queue_storage_logs:
