services:
  php:
    image: php-app:latest
    build:
      context: .
      args:
        APP_URL: ${APP_URL}
        REVERB_APP_KEY: ${REVERB_APP_KEY}
        REVERB_HOST: ${REVERB_HOST}
    environment:
      - PHP_OPCACHE_ENABLE=1
      - AUTORUN_ENABLED=true
      - SERVICE_FQDN_SERVER=https://cwk.sh
      - _APP_URL=$SERVICE_FQDN_SERVER
      - SERVICE_FQDN_APPWRITE_8080
    volumes:
      - "storage_private:/var/www/html/storage/app/private/"
      - "storage_public:/var/www/html/storage/app/public/"
      - "storage_sessions:/var/www/html/storage/framework/sessions"
      - "storage_logs:/var/www/html/storage/logs"

volumes:
  certificates:
  storage_private:
  storage_public:
  storage_sessions:
  storage_logs:
