services:
  php:
    image: php-app:latest
    build:
      context: .
      args:
        APP_URL: ${APP_URL}
        REVERB_APP_KEY: ${REVERB_APP_KEY}
        REVERB_HOST: ${REVERB_HOST}
    environment:
      PHP_OPCACHE_ENABLE: 1
      AUTORUN_ENABLED: true
    volumes:
      - "storage_private:/var/www/html/storage/app/private/"
      - "storage_public:/var/www/html/storage/app/public/"
      - "storage_sessions:/var/www/html/storage/framework/sessions"
      - "storage_logs:/var/www/html/storage/logs"


  reverb:
    depends_on:
      - php
    image: php-app:latest
    environment:
      PHP_OPCACHE_ENABLE: 1
      AUTORUN_ENABLED: false
      LOG_CHANNEL: stderr
    command: [ "php", "/var/www/html/artisan", "--port=8000", "reverb:start" ]
    stop_signal: SIGTERM
    healthcheck:
      test: [ "CMD", "healthcheck-reverb" ]
      start_period: 10s
    volumes:
      - "reverb_storage_private:/var/www/html/storage/app/private/"
      - "reverb_storage_public:/var/www/html/storage/app/public/"
      - "reverb_storage_sessions:/var/www/html/storage/framework/sessions"
      - "reverb_storage_logs:/var/www/html/storage/logs"

volumes:
  certificates:
  storage_private:
  storage_public:
  storage_sessions:
  storage_logs:

  reverb_storage_private:
  reverb_storage_public:
  reverb_storage_sessions:
  reverb_storage_logs:
